server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  type-aliases-package: com.stableforever.mybatis.encryption.alias
  type-handlers-package: com.flycat.mybatisencryptiondemo.handler